### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by fourmat4** [rileypeterson/Depop#2]
Hi! while trying to run the script i get this permission error 

`Traceback (most recent call last):
  File "C:\Users\court\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin =PIPE)
  File "C:\Users\court\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\court\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied`

I am aware this is not an error with your script, but i was wondering if you could help me resolve this. As i have no experience with selenium. 

Ps - thanks for making this public, i have been searching for a bot for my depop shop for some time!

**Comment by rileypeterson** [comment]
What did you put for this variable in your script?

`chrome_path = r"your\path\to\chromedriver.exe"`

for example mine would be:

`chrome_path = r"C:\Users\Riley Peterson\Downloads\chromedriver.exe"`

I ask because it looks similar to this [traceback](https://stackoverflow.com/questions/38959885/python-selenium-permissionerror-winerror-5-access-is-denied). Otherwise I might try running as administrator/sudo. Also just making [this warning](https://github.com/rileypeterson/Depop/blob/master/README.md#warning) extra clear.

**Comment by rileypeterson** [comment]
Closing if no response.
