### ISSUE TITLE
Issue when running

### ISSUE THREAD

**Issue by bontoft** [rileypeterson/Depop#3]
When I run the module I am getting the following error:

============= RESTART: C:/Users/thomas/Documents/Depop/depop.py =============
Traceback (most recent call last):
  File "C:/Users/thomas/Documents/Depop/depop.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
>>> 

Any ideas?

**Comment by rileypeterson** [comment]
Selenium is a python package. You need to have it installed on your system in order to run the script. I updated the instructions to include this step.

So try running `pip install selenium` in a terminal/command prompt. 

Or with conda: `conda install selenium`

Here's some info about [PIP](http://www.pythonforbeginners.com/basics/python-pip-usage) and [python packages](https://docs.python.org/3/installing/). 

Also FYI, if you search this error on google (i.e. `ModuleNotFoundError: No module named 'selenium'`) the first result is [exact what you need to do](https://stackoverflow.com/questions/31147660/importerror-no-module-named-selenium)

Stack overflow is your friend.
