### ISSUE TITLE
Error When Running

### ISSUE THREAD

**Issue by ChrisPotts** [rileypeterson/Depop#4]
`Traceback (most recent call last):
  File "/Users/Chris/Documents/Depop Follow:Unfollow.py", line 23, in <module>
    prof_follower_elm = driver.find_element_by_xpath("""//span[contains(text(),'Followers')]""").find_element_by_xpath("..")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),'Followers')]"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.6 x86_64)`

**Comment by ChrisPotts** [comment]
I have logged into my depop account and pressed enter at this point

**Comment by ChrisPotts** [comment]
I then enter follow, it waits and then it does this

**Comment by ChrisPotts** [comment]
Potentially Depop have changed their site???

**Comment by rileypeterson** [comment]
@ChrisPotts I just tried without being logged in (since I no longer have an account) and it worked as expected (got at least to line 131... so I don't think they have changed their site. It seems like in your case its failing to find the element "_## Followers_" which is displayed on a users profile. Perhaps you could paste the xpath of that element here. For me it's: `//*[@id="mount"]/div/div/div[3]/div/div[1]/div[2]/div/div/span[1]/span[2]`. 
Maybe you can give some more detail... 
Here's the expected output from the script:
```
Type in login details, then press enter, then press enter to continue running script

select mode (following, unfollowing):following
data-css-l977c9

First username to use:crossover_sportswear
hit break button <-- (happens to me since not logged in...)
Done following crossover_sportswear followers. Followed 1 users.
```

As always, here is the [warning](https://github.com/rileypeterson/Depop#warning) for using this script.

**Comment by rileypeterson** [comment]
@ChrisPotts closing if no response...
