### ISSUE TITLE
"No Module..."

### ISSUE THREAD

**Issue by Rashaadonimous** [rileypeterson/Depop#5]
I have come across your code for a follower bot on the application "Depop". This was done using the application Python. I have copied and pasted your code into a new python file, changed the directories to suite mine on my pc  but I still have an error. I will include a screenshot below. Your help would be appreciated. (The first 5 lines of code have not been touched). I have only changed the chormepath and the home user.
![dpop bot screenshot 1](https://user-images.githubusercontent.com/43256421/45523548-bc44d980-b7c1-11e8-8d4d-968afc86a264.png)

**Comment by rileypeterson** [comment]
@Rashaadonimous 

You are receiving this error because the `selenium` module is not installed.

From step one of the instructions:

> Be sure to `pip install selenium` or with conda: `conda install selenium`

[Here](https://programminghistorian.org/en/lessons/installing-python-modules-pip) is a brief tutorial about installing modules using `pip`. From the [python docs](https://docs.python.org/3/installing/index.html)

**Comment by Rashaadonimous** [comment]
Many thanks mate. Installed pip and then selenium through pip. Went on to run the program and got hit with the screenshot below...got anything to help?

So sorry and many thanks mate

![image](https://user-images.githubusercontent.com/43256421/45570829-09758980-b85c-11e8-8da8-872c5a2e95ac.png)

**Comment by rileypeterson** [comment]
Since you are presumably on windows, your `chrome_path` variable should end in `.exe` and it should point to the executable for [Chromedriver](http://chromedriver.chromium.org/). So:
#### This line is incorrect
`chrome_path = r'C:\webdrivers'`

Typically things downloaded show up in your downloads folder. So I suggest looking there for chromedriver. When you find it hold shift and right click, then click copy as path, paste that as the variable for `chrome_path`.

**Comment by rileypeterson** [comment]
Closing as abandoned, if no response

**Comment by WhiteLew** [comment]
Hi I am having trouble with this code! i keep getting this error. any help? i keep getting (winError 5) accessed denied - however my file location for chromedriver is correct. 
I also get a permission error
![code error](https://user-images.githubusercontent.com/64641671/80803363-eff89100-8ba9-11ea-970b-76739f64b23f.JPG)

**Comment by WhiteLew** [comment]
hi mate so ive got it running, however I am now getting this error 
DevTools listening on ws://127.0.0.1:64091/devtools/browser/c11134e1-45d5-468c-a5c6-2277b9565234
[1489472:1489528:0501/133940.338:ERROR:browser_switcher_service.cc(238)] XXX Init()
Type in login details, then press enter, then press enter to continue running script
select mode (following, unfollowing):unfollowing
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    driver.get('https://www.depop.com/'+thewhiteworks)
NameError: name 'thewhiteworks' is not defined
PS C:\Users\whiii\desktop\depop-master>

Any help? this is my code 
![depop error new](https://user-images.githubusercontent.com/64641671/80806147-c5123b00-8bb1-11ea-80a6-6e9e38eeb55a.JPG)

**Comment by rileypeterson** [comment]
https://github.com/rileypeterson/Depop#status
